### ISSUE TITLE
Add Controller Validations

### ISSUE THREAD

**Issue by gabriellopes00** [diego3g/umbriel#52]
Can the controller validations be made by creating a validator component within each module that requires a validation ? Example: Inside Account's modules, the RegisterUser controller needs a validator. Would be a good idea create a component called `validator` with the rules to validate the email, the user name, to compare password and password_confirmation... inside account's module, and inject that dependency inside de controller. This way, inside the controller, just call `this.validator.validate(email...)`. What do you think ?

**Comment by diego3g** [comment]
Hey @gabriellopes00, can u provide some example about that?

**Comment by gabriellopes00** [comment]
Of course, @diego3g. I'll work on it.

**Comment by gabriellopes00** [comment]
@diego3g Some days ago, i provided some example of a controller validator, implementing a validator to RegisterUserController with my logic, but I've been analyzing the project further and concluded that my implementation has a lot of redundant code, since I'm repeating the project domain validation in the controller validation. I'm going to reimplement the validators, and instead of validating the email format or the password length (things that are already being done in the project domain), I'm going to create a validator to validate the required controller parameters and their required types. I'll be working on the implementation and I'll bring something soon 👊

**Comment by diego3g** [comment]
Thanks @gabriellopes00!

**Comment by gabriellopes00** [comment]
@diego3g Dude, i redid the implementation of validators, see #69. What do you think ?
